# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Down < Formula
  desc ""
  homepage "https://github.com/SantiagoBedoya/down"
  version "0.5"

  on_macos do
    url "https://github.com/SantiagoBedoya/down/releases/download/v0.5/down_0.5_darwin_all.tar.gz"
    sha256 "e52e1c64b9b64549cffd7ce270bf8638b01c6f3e445505473503aac9d30a16b7"

    def install
      bin.install "down"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SantiagoBedoya/down/releases/download/v0.5/down_0.5_linux_arm64.tar.gz"
      sha256 "f5e5d2c6ac10fe1299935b5111148317eade034adba2f4eaf8e5e05e6a96bae7"

      def install
        bin.install "down"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SantiagoBedoya/down/releases/download/v0.5/down_0.5_linux_amd64.tar.gz"
      sha256 "0a02254a95c8a1fb638f1325830ba0590210cc5815e868c6acd907acaf0017ae"

      def install
        bin.install "down"
      end
    end
  end
end
